apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: qotd
  name: qotd
spec:
  ports:
  - port: 5000
    protocol: TCP
    targetPort: 5000
  selector:
    app: qotd
status:
  loadBalancer: {}

